apps/conta/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from .views import UsuarioCreate, LoginView, LogoutView, ListaUsuario


router = routers.DefaultRouter()
router.register('usuarios', ListaUsuario)


urlpatterns = [
    path('', include(router.urls)),
    path('criar/', UsuarioCreate.as_view(), name='usuario_create'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/moedas/urls.py
from django.urls import path, include
from .views import ConsultaCriptoMoedaView, ConsultaMoedaFisicaView, MoedasView
from rest_framework import routers

router = routers.DefaultRouter()
router.register('moedas', MoedasView)

urlpatterns = [
    path('', include(router.urls)),
    path('cripto-moeda/consulta/', ConsultaCriptoMoedaView.as_view(), name='consulta_criptomoeda'),
    path('moeda-fisica/consulta/', ConsultaMoedaFisicaView.as_view(), name='consulta_moedafisica'),
]

cotacoes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('conta/', include('apps.conta.urls')),
    path('moedas/', include('apps.moedas.urls')),
    path('', login_required(TemplateView.as_view(template_name='index.html')), name='index')
]

apps/conta/models.py
from django.db import models
from django.contrib.auth.models import User


class users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

apps/moedas/models.py
from django.db import models


class Moeda(models.Model):
    class Meta:
        verbose_name = 'Moeda'
        verbose_name_plural = 'moedas'

    nome = models.CharField('Nome', max_length=100)

    def __str__(self):
        return self.nome

apps/conta/forms.py
from django import forms
from django.forms.utils import ErrorList
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from .models import users


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nome'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Senha'})

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.username = instance.first_name
        instance.set_password(instance.password)
        if commit:
            instance.save()
        return instance


class LoginForm(forms.Form):
    _user = None
    usuario = forms.CharField(label="Usuário", widget=forms.TextInput(attrs={'tabindex': 1, 'class': 'form-control',
                                                                             'placeholder': 'Nome'}))
    senha = forms.CharField(label="Senha", max_length=20, widget=forms.PasswordInput(attrs={'tabindex': 2,
                                                                                            'class': 'form-control',
                                                                                             'placeholder': 'Senha'}))

    def clean(self):
        cleaned_data = self.cleaned_data
        if 'usuario' in cleaned_data and 'senha' in cleaned_data:
            self._user = authenticate(username=cleaned_data['usuario'], password=cleaned_data['senha'])
            if not self._user:
                self._errors["usuario"] = ErrorList(["Usuário e/ou senha inválido."])
        return cleaned_data

    @property
    def user(self):
        return self._user

apps/moedas/forms.py
from django import forms


CRIPTO_MOEDAS_CHOICES = [
    ('bitcoin', 'Bitcoin'),
    ('ethereum', 'Ethereum'),
    ('bitcoin-cash', 'Bitcoin Cash'),
    ('stellar', 'Stellar'),
]


MOEDAS_FISICAS_CHOICE = [
    ('USD', 'Dólar Comercial'),
    ('CAD', 'Dólar Canadense'),
    ('EUR', 'Euro'),
    ('GBP', 'Libra Esterlina'),
]

class CriptoMoedasForm(forms.Form):
    moeda = forms.ChoiceField(label='Cripto Moeda', choices=CRIPTO_MOEDAS_CHOICES,
                              widget=forms.Select(attrs={'class': 'form-control'}))


class MoedasFisicaForm(forms.Form):
    moeda = forms.ChoiceField(label='Moedas Físicas', choices=MOEDAS_FISICAS_CHOICE,
                              widget=forms.Select(attrs={'class': 'form-control'}))

apps/conta/views.py
from django.contrib.auth.models import User
from django.views.generic import CreateView, View
from django.urls.base import reverse_lazy, reverse
from django.shortcuts import HttpResponseRedirect, render
from django.contrib.auth import logout, login
from .forms import UserForm, LoginForm
from rest_framework import viewsets
from .serializers import UsuarioSerializer
from .models import User


class UsuarioCreate(CreateView):
    model = User
    form_class = UserForm
    template_name = 'conta/usuario_form.html'

    def get_success_url(self):
        return reverse('index')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login'))


class LoginView(View):
    def get(self, request, *args, **kwargs):
        form = LoginForm()
        #habilita teste de cookie
        request.session.set_test_cookie()
        return render(request, 'conta/login.html', locals())

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if not request.session.test_cookie_worked():#teste cookie
            form.add_error('usuario', 'Por favor habilite os cookies.')
        elif form.is_valid():
            #finaliza test com cookie
            request.session.delete_test_cookie()
            retorno = 'next' in request.GET and request.GET['next'] or reverse('index')
            login(request, form.user)
            request.session.set_expiry(0)
            return HttpResponseRedirect(retorno)
        return render(request, 'conta/login.html', locals())


class ListaUsuario(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UsuarioSerializer

apps/moedas/views.py
from django.views.generic import View
from django.shortcuts import render, HttpResponse
from django.template import loader
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CriptoMoedasForm, MoedasFisicaForm
from rest_framework import viewsets
from .serializers import MoedaSerializer
from .models import Moeda
import json
import requests


class ConsultaCriptoMoedaView(LoginRequiredMixin, View):
    template_name = 'moedas/cripto/consulta.html'
    page_template = 'moedas/cripto/resultado.html'
    cripto_api = 'https://api.coinmarketcap.com/v1/ticker/{}'

    def get(self, request, *args, **kwargs):
        form = CriptoMoedasForm()
        response = dados = None
        d = {}
        if request.is_ajax():
            form = CriptoMoedasForm(request.GET)
            form.is_valid()
            r = requests.get(self.cripto_api.format(form.cleaned_data['moeda']))
            if r.status_code == requests.codes.ok:
                try:
                    dados = json.loads(r.content)[0]
                    d['chart_data'] = [dados['percent_change_1h'], dados['percent_change_24h'], dados['percent_change_7d']]
                except:
                    dados = None
            d['html'] = loader.get_template(self.page_template).render({'dados': dados})
            response = HttpResponse(json.dumps(d), content_type='application/json')
        else:
            response = render(request, self.template_name, locals())
        return response


class ConsultaMoedaFisicaView(LoginRequiredMixin, View):
    template_name = 'moedas/fisica/consulta.html'
    page_template = 'moedas/fisica/resultado.html'
    moeda_api = 'https://economia.awesomeapi.com.br/json/{}'

    def get(self, request, *args, **kwargs):
        form = MoedasFisicaForm()
        dados = None
        if request.is_ajax():
            form = MoedasFisicaForm(request.GET)
            form.is_valid()
            r = requests.get(self.moeda_api.format(form.cleaned_data['moeda']))
            if r.status_code == requests.codes.ok:
                try:
                    dados = json.loads(r.content)[0]
                except:
                    dados = None
            self.template_name = self.page_template
        return render(request, self.template_name, locals())


class MoedasView(viewsets.ModelViewSet):
    queryset = Moeda.objects.all()
    serializer_class = MoedaSerializer

cotacoes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Cotações</title>
        <!-- plugins:css -->
        <link rel="stylesheet" href="{% static 'theme/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'theme/vendors/css/vendor.bundle.base.css' %}">
        <!-- endinject -->
        <!-- inject:css -->
        <link rel="stylesheet" href="{% static 'theme/css/style.css' %}">
        <!-- endinject -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    </head>
    <body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" href="{% url 'index' %}">Cotações</a>
                <a class="navbar-brand brand-logo-mini" href="{% url 'index' %}">Cotações</a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item d-none d-lg-block full-screen-link">
                        <a class="nav-link" href="{% url 'consulta_criptomoeda' %}">
                            Cripto Moedas
                        </a>
                    </li>
                    <li class="nav-item d-none d-lg-block full-screen-link">
                        <a class="nav-link" href="{% url 'consulta_moedafisica' %}">
                            Moedas Física
                        </a>
                    </li>

                    <li class="nav-item nav-profile dropdown">

                        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                            <div class="nav-profile-text nav-profile-img">
                                <p class="mb-1 text-black d-inline-block">
                                    {{ request.user.first_name|default:'' }}

                                </p>
                                <span class="availability-status online"></span>
                            </div>
                        </a>
                        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">
                                <i class="mdi mdi-logout mr-2 text-primary"></i>
                                Sair
                            </a>
                        </div>
                    </li>
                    <li class="nav-item d-none d-lg-block full-screen-link">
                        <a class="nav-link">
                            <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                        </a>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <div class="main-panel">
            <div class="content-wrapper">
                {% block content %}
                {% endblock %}
            </div>
            <footer class="footer text-center">
                <span class="text-muted d-block d-sm-inline-block">Copyright © {% now 'Y' %}</span
            </footer>
        </div>
        <!-- main-panel ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'theme/vendors/js/vendor.bundle.base.js' %}"></script>
    <script src="{% static 'theme/vendors/js/vendor.bundle.addons.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="{% static 'theme/js/off-canvas.js' %}"></script>
    <script src="{% static 'theme/js/misc.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="{% static 'js/dashboard.js' %}"></script>
    <!-- End custom js for this page-->
    {% block scripts %}
    {% endblock %}
    </body>
</html>

cotacoes/templates/conta/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Cotações</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'theme/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'theme/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'theme/css/style.css' %}">
    <!-- endinject -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
</head>
<body>
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
            <div class="row w-100">
                <div class="col-lg-4 mx-auto">
                    <div class="auth-form-light text-left p-5">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<!-- plugins:js -->
<script src="{% static 'theme/vendors/js/vendor.bundle.base.js' %}"></script>
<script src="{% static 'theme/vendors/js/vendor.bundle.addons.js' %}"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{% static 'theme/js/off-canvas.js' %}"></script>
<script src="{% static 'theme/js/misc.js' %}"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<!-- End custom js for this page-->
{% block scripts %}
{% endblock %}
</body>
</html>

cotacoes/templates/conta/login.html
{% extends "conta/base.html" %}
{% block content %}
    <div class="brand-logo">
        Cotações
    </div>
    <h4>Olá! Vamos começar.</h4>
    <h6 class="font-weight-light">Efetue o login para continuar.</h6>
    <form class="pt-3" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.usuario }}
        </div>
        <div class="form-group">
            {{ form.senha }}
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn">
                Entrar
            </button>
        </div>
        <div class="text-center mt-4 font-weight-light">
            Faça seu cadastro <a href="{% url 'usuario_create' %}" class="text-primary">AQUI</a>
        </div>
    </form>
{% endblock %}

cotacoes/templates/conta/usuario_form.html
{% extends "conta/base.html" %}
{% block content %}
    <h4>Olá! Vamos fazer o seu cadastro.</h4>
    <form class="pt-3" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.first_name }}
        </div>
        <div class="form-group">
            {{ form.password }}
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn">
                Salvar
            </button>
        </div>
    </form>
{% endblock %}

cotacoes/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <p>
        oi eu estou no index
    </p>
{% endblock %}

cotacoes/templates/moedas/cripto/consulta.html
{% extends 'base.html' %}
{% block content %}
    <div class="row mt-5">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Consultar Cripto Moeda</h4>
                    <p class="card-description">
                        Selecione a Cripto Moeda que deseja cotar
                    </p>
                    <form id="form" class="forms-sample" action="" method="GET">
                        <div class="form-group">
                            <label>{{ form.moeda.label }}</label>
                            {{ form.moeda }}
                        </div>
                    </form>
                    <canvas id="lineChart" style="height:250px"></canvas>
                </div>
            </div>
        </div>
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body" id="resultado"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script type="application/javascript">
        var form = $("#form");
        var options = {
            scales: {
              yAxes: [{
                ticks: {
                  beginAtZero: true
                }
              }]
            },
            legend: {
              display: false
            },
            elements: {
              point: {
                radius: 0
              }
            }

          };
        $(function (){
            $("#id_moeda").change(function (){
                $.ajax({
                    'url': form.attr("action"),
                    'method': form.attr("method"),
                    'data': form.serialize(),
                    'success': function (data){
                        $("#resultado").html(data.html);
                        var data_chart = {
                            labels: ["1 hora", "24 horas", "7 dias"],
                            datasets: [{
                              label: 'Variação (%)',
                              data: data.chart_data,
                              backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                              ],
                              borderColor: [
                                'rgba(255,99,132,1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                              ],
                              borderWidth: 1,
                              fill: false
                            }]
                          };
                        var lineChartCanvas = $("#lineChart").get(0).getContext("2d");
                        var lineChart = new Chart(lineChartCanvas, {
                          type: 'line',
                          data: data_chart,
                          options: options
                        });

                    }
                });
            });
        });

    </script>
{% endblock %}

cotacoes/templates/moedas/cripto/resultado.html
{% if dados %}
    <table class="table">
        <tbody>
            <tr>
                <td>Nome</td>
                <td>{{ dados.name|default:' - ' }}</td>
            </tr>
            <tr>
                <td>Símbolo</td>
                <td>{{ dados.symbol|default:' - ' }}</td>
            </tr>
            <tr>
                <td>Rank</td>
                <td>{{ dados.rank|default:' - ' }}</td>
            </tr>
            <tr>
                <td>Preço USD</td>
                <td>{{ dados.price_usd|default:' - ' }}</td>
            </tr>
            <tr>
                <td>Preço Bitcoin</td>
                <td>{{ dados.price_btc|default:' - ' }}</td>
            </tr>
            <tr>
                <td>Volume USD 24H</td>
                <td>{{ dados.24h_volume_usd|default:' - ' }}</td>
            </tr>
                <td><i>"Market Cap USD"</i> (Moeda X Preço)</td>
                <td>{{ dados.market_cap_usd|default:' - ' }}</td>
            </tr>
                <td>Total de Moedas válidas</td>
                <td>{{ dados.available_supply|default:' - ' }}</td>
            </tr>
            </tr>
                <td>Total de Moedas criadas </td>
                <td>{{ dados.total_supply|default:' - ' }}</td>
            </tr>
            </tr>
                <td>Total de moedas possíveis</td>
                <td>{{ dados.max_supply|default:' - ' }}</td>
            </tr>
        </tbody>
    </table>
{% else %}
    <p>
        {{ msg }}
    </p>
{% endif %}

cotacoes/templates/moedas/fisica/consulta.html
{% extends 'base.html' %}
{% block content %}
    <div class="row mt-5">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Consultar Moeda Física</h4>
                    <p class="card-description">
                        Selecione a Moeda Física que deseja cotar
                    </p>
                    <form id="form" class="forms-sample" action="" method="GET">
                        <div class="form-group">
                            <label>{{ form.moeda.label }}</label>
                            {{ form.moeda }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body" id="resultado"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script type="application/javascript">
        var form = $("#form");
        $(function (){
            $("#id_moeda").change(function (){
                $.ajax({
                    'url': form.attr("action"),
                    'method': form.attr("method"),
                    'data': form.serialize(),
                    'success': function (data){
                        $("#resultado").html(data);

                    }
                });
            });
        });

    </script>
{% endblock %}

cotacoes/templates/moedas/fisica/resultado.html
{% if dados %}
    <table class="table">
        <tbody>
            <tr>
                <td>Nome</td>
                <td>{{ dados.name|default:' - ' }}</td>
            </tr>
            <tr>
                <td>Símbolo</td>
                <td>{{ dados.code|default:' - ' }}</td>
            </tr>
            <tr>
                <td>Alta (R$)</td>
                <td>{{ dados.high|default:' - ' }}</td>
            </tr>
            <tr>
                <td>Baixa (R$)</td>
                <td>{{ dados.low|default:' - ' }}</td>
            </tr>

        </tbody>
    </table>
{% else %}
    <p>
        {{ msg }}
    </p>
{% endif %}